### ISSUE TITLE
Strange issue with specific table

### ISSUE THREAD

**Issue by maleet** [zzzprojects/EntityFramework-Extensions#19]
I have table "Manufacturing.ProductOrder" and this resolved with exception on BulkSaveChanges
Invalid object name 'ProductionOrder'.
What is the best way to figure out internal problems? LogDump? EF works nicely with my model, BulkSaveChanges have problems.

**Comment by maleet** [comment]
From profiler:
```
exec sp_executesql N'
/* CREATE TEMPORARY TABLE */
SELECT TOP 0 * INTO #2f50d97bf16848dc8740f66ff4f96dcf FROM [ProductionOrder]


/* SELECT column information */
SELECT  DestinationTable.Name AS DestinationName ,
        C.name AS ColumnName ,
        C.column_id AS ColumnOrder ,
        C.precision AS Precision ,
        C.scale AS Scale ,
        C.max_length AS MaxLength ,
        C.collation_name AS Collation ,
        C.Is_Identity AS IsIdentity ,
        ( CASE WHEN EXISTS ( SELECT 1
                             FROM   tempdb.sys.index_columns AS X
                             WHERE  X.index_id = B.index_id
                                    AND X.object_id = B.object_id
                                    AND X.column_id = C.column_id ) THEN 1
               ELSE 0
          END ) AS IsPrimaryKey ,
        C.system_type_id AS System_Type_Id ,
        LOWER(D.Name) AS TypeName,
        0 AS IsSynonym,
        D.is_user_defined,
        F.name
FROM    (SELECT @Table_0 AS Name, @Table_Temp_0 AS TempName) AS DestinationTable
        INNER JOIN tempdb.sys.tables   AS A ON A.object_id = OBJECT_ID(''tempdb..'' + DestinationTable.TempName)
        LEFT JOIN tempdb.sys.indexes   AS B ON B.object_id = A.object_id
                                        AND B.is_primary_key = 1
        INNER JOIN tempdb.sys.columns  AS C ON C.object_id = A.object_id
        INNER JOIN tempdb.sys.types    AS D ON D.system_type_id = C.system_type_id
                                     AND D.user_type_id = C.user_type_id
        INNER JOIN sys.schemas AS F ON D.schema_id = F.schema_id
ORDER BY DestinationName ,
        ColumnOrder

/* DROP TEMPORARY TABLE */
DROP TABLE #2f50d97bf16848dc8740f66ff4f96dcf

',N'@Table_0 nvarchar(17),@Table_Temp_0 nvarchar(33)',@Table_0=N'[ProductionOrder]',@Table_Temp_0=N'#2f50d97bf16848dc8740f66ff4f96dcf'
```

Looks like [ProductionOrder] is missing schema info?

**Comment by zzzprojects** [comment]
Hello Maleet,

You are right. For an unknown reason, the schema name in your case is not taken by our library.

Is this possible to send us your model to help us to understand and fix this issue? info@zzzprojects.com

**Database First** 
Simply send us your .edmx file.

**Code First**
You can get the model string with the following method

``` csharp
public string GetModelXDocument(DbContext context)
{
    XDocument doc;
    using (var memoryStream = new MemoryStream())
    {
        using (XmlWriter xmlWriter = XmlWriter.Create(memoryStream, new XmlWriterSettings { Indent = true }))
        {
            EdmxWriter.WriteEdmx(context, xmlWriter);
        }

        memoryStream.Position = 0;

        doc = XDocument.Load(memoryStream);
    }
    return doc.ToString();
}
```

Best Regards,

Jonathan

**Comment by maleet** [comment]
I use Code First, so I sent you edmx from model to email.

**Comment by zzzprojects** [comment]
Unfortunately, everything looks fine in your model.

Can you try the same example below? If you map your schema differently, let us know how you did it.

We will for sure try to fix it ASAP when we will be able to reproduce a similar issue.

```csharp
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Windows.Forms;

namespace Z.EntityFramework.Extensions.Lab
{
    public partial class Form_Issue_Schema : Form
    {
        public Form_Issue_Schema()
        {
            InitializeComponent();

            using (var ctx = new CurrentContext())
            {
                ctx.EntitySimple1s.Add(new EntitySimple1() {IntColumn = 1});
                ctx.EntitySimple2s.Add(new EntitySimple2() {IntColumn = 2});

                ctx.BulkSaveChanges();
            }
        }

        public class CurrentContext : DbContext
        {
            public CurrentContext()
                : base("CodeFirstEntities")
            {
            }

            public DbSet<EntitySimple1> EntitySimple1s { get; set; }
            public DbSet<EntitySimple2> EntitySimple2s { get; set; }

            protected override void OnModelCreating(DbModelBuilder modelBuilder)
            {
                modelBuilder.Entity<EntitySimple2>().ToTable("Issue_Schema_EntitySimple2", "Manufacturing");

                base.OnModelCreating(modelBuilder);
            }
        }

        [Table("Issue_Schema_EntitySimple1", Schema = "Manufacturing")]
        public class EntitySimple1
        {
            public int ID { get; set; }

            public int IntColumn { get; set; }
        }

        public class EntitySimple2
        {
            public int ID { get; set; }

            public int IntColumn { get; set; }
        }
    }
}
```

**Comment by maleet** [comment]
I created solution with similar structure and it was working... Then I used also my ef context wrapper and got similar problems there. So I looked more in wrapper and there it was... 

`useEntityFrameworkPropagation` is the key. I tried performance testing and with this turned of performance was really impressive. Then I start using it everywhere and I got problems... So try schema handling with useEntityFrameworkPropagation set to false.

Code: https://bitbucket.org/maleet/z.entityframework/overview

There are some issues with same table deletion also. I don't get 
`Invalid object name 'ProductionOrder'.`
here, but these are connected, because in other project with useEntityFrameworkPropagation as false I still get this error and with useEntityFrameworkPropagation as true it's working.

**Comment by zzzprojects** [comment]
Thank you,

The issue has been found. We forget to add the schema name in a special situation which happens in your scenario.

We will make some additional test/check and release a new version within a few hours or tomorrow morning.

Best Regards,

Jonathan

**Comment by zzzprojects** [comment]
The version 3.10.23 has been released
https://www.nuget.org/packages/Z.EntityFramework.Extensions/

The issue with the schema name should be fixed. Every method requesting the table name now use the same method to include the schema.

We didn't successfully reproduce the bug in code you provided since we were receiving another error.

Let us know if the schema issue is fixed.

---
Concerning disabling the option useEntityFrameworkPropagation , I don't think this will work in your case. It seems our logic fail with your model.

We are currently re-writing the library to support .NET Core so I don't think it worth the time to fix this issue. However, It will be for sure fixed in the next major version.

Do you still get good performance with BulkSaveChanges? (without disabling the useEntityFrameworkPropagation).

Best Regards,

Jonathan

**Comment by maleet** [comment]
As I have quite a huge graph with navigations all around (even almost cyclic ones as new objects are referencing each other) then it takes huge amount of memory and it is quite slow. Order of INSERT-s is still wrong (as I get exception with insert) so I try to figure out better solution. It's quite difficult to figure out which is this exact object - I have table name and like 3000 entries to insert and one of them is failing. Maybe with sqlprofiler I could get more information... 

Now I'm thinking of figuring out new objects by myself and BulkInsert then based on dependencies. I have changed and new objects in EF context (it takes quite a lot of time to put then there) so I could query local objects based on their state. For this there are couple of free solutions also so I was hoping to get a "silver bullet" what would just save everything, but 100 times quicker :) 

In the end I would like to have huge amount of detached objects, change them and store them in memory/documentDB/file and with some user action write all changes back to database. It looks like DocumentDB would fit even better for my case, but other external system want to use sql based views and it takes a lot of effort to create api endpoints to them.

**Comment by zzzprojects** [comment]
Yup, your graph is pretty intense with all theses navigations ;)

Our next major version will for sure support it, but it will not be ready until early 2017.

Do you still get the insert error with SaveChanges and BulkSaveChanges() or only with BulkSaveChanges(false)?

And if it works, what kind of performance do you get with BulkSaveChanges()?

**Comment by maleet** [comment]
It took lot of time, but SaveChanges completed successfully. There are problems with both Bulk methods. Kind of maybe it's data related, but EF figured out correct way to do it. For now I splitted my save logic to multiple steps and try this way. Still with BulkInsert, BulkUpdate, but with correct order controlled by my logic.

**Comment by zzzprojects** [comment]
> It took lot of time, but SaveChanges completed successfully

What's a lot of time for your case? Do you count only the BulkSaveChanges time or include everything?(Retrieving, creating, adding entities)

One of the most frequent people do is poorly using the Add method. Most people don't believe it make a difference, but in fact, it makes a HUGE difference. See: http://www.zzzprojects.com/entity-framework/how/performance-add

If you believe a part of the performance issue could not be related to the BulkSaveChanges and it's possible to you to share some code (doesn't need to work or be cleaned, as long as it's possible to understand it), I will be happy to look at it to see if I can find some performance bottleneck.

**Comment by maleet** [comment]
I was counting only SaveChanges. With lot of objects and one by one insert commands it is slow.

I use AddRange and without AutoDetectChanges. Now I try to split it. I have objects detached so it should be possible to handle these. Still the object graph is quite intense. 

I finish my current ideas. I already found one code related problem... so at the end maybe it's still my mistake :)

But sure I can share some code, but that comes maybe in next week

**Comment by JonathanMagnan** [comment]
Hello @maleet ,

Do you still get the issue?

Can we close it?

**Comment by maleet** [comment]
As I use different solution now then I don't have this issue. 

I still got this issue before switching to another solution :)
It can be closed yes.

**Comment by JonathanMagnan** [comment]
Closing comment: confirmed
