### ISSUE TITLE
SqlLite In-memory Add BulkSaveChanges failure

### ISSUE THREAD

**Issue by armitagemderivitec** [zzzprojects/EntityFramework-Extensions#216]
### Description
When inserting an object and using the BulkSaveChanges method I am met with the following an error.

### Exception
```
System.Exception : An error occured while resolving mapping by name. See the inner exception for details
  ----> System.Exception : Missing Colum : Id
On entity : Object
On Table : "dbo.Groups"
   at Z.BulkOperations.BulkOperation.()
   at Z.BulkOperations.BulkOperation.Execute()
   at .[](DbContext this, IEnumerable`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, StateManager , IReadOnlyList`1 , Action`1 )
   at .(DbContext this, Action`1 )
   at Derivitec.Infrastructure.Data.Db.Models.PortfolioDbContext.SaveChanges()
   at Derivitec.Infrastructure.Data.PortfolioRepository.Add(Portfolio entity)
```

### Further technical details
- EF version: EFCore 2.2
- EF Extensions version: 2.2.7
- Database Provider: SqlLite In-memory

**Comment by JonathanMagnan** [comment]
Hello @armitagemderivitec ,

Thank you for reporting.

We do not support SQLite in memory (we have not done any test). So we will look at it.

Best Regards,

Jonathan

**Comment by armitagemderivitec** [comment]
@JonathanMagnan your help is appreciated as always

**Comment by armitagemderivitec** [comment]
I wonder if it's something to do with me using IEntityTypeConfiguration<TEntity> configuration as oppose to model builders...

**Comment by JonathanMagnan** [comment]
Hello @armitagemderivitec ,

My developer made a few simple cases and everything is working as expected.

Do you think you could provide us a runnable project/solution that reproduces it?

That will help my developer to find out why that's happening.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @armitagemderivitec ,

I don't think we received any project yet, should we close this issue?

**Comment by armitagemderivitec** [comment]
Hi @JonathanMagnan,

Apologies for not getting this to your sooner. We've been working on a large release. I'll aim to get you this by the end of the week.

Thanks

**Comment by armitagemderivitec** [comment]
Hi @JonathanMagnan,

I've just published the code to a private repo with a single failing test demonstrating the issue. I've added you as a contributor.

Many thanks in advance.

**Comment by JonathanMagnan** [comment]
Great, thank you ;)

**Comment by JonathanMagnan** [comment]
Hello @armitagemderivitec ,

We finally find out the issue. It seems the `memory` provider doesn't care at all about the schema name (`dbo` in your case).

We still need to perform a few more test but we highly believe a fix will be available tomorrow.

**Comment by armitagemderivitec** [comment]
@JonathanMagnan thanks for looking into it, looking forward to the fix :)

**Comment by JonathanMagnan** [comment]
Hello @armitagemderivitec ,

The v2.6.2 has been released.

Could you try it and let us know if everything is working as expected?

No code for supporting `memory` in `sqlite` was existing before so it might still have a few issues that we don't know.
